from django.db import models

# Create your models here.
class UserSettings(models.Model):
    val1name=models.CharField(max_length=30,default="",blank=True)
    val2name=models.CharField(max_length=30,default="",blank=True)
    val3name=models.CharField(max_length=30,default="",blank=True)
    val4name=models.CharField(max_length=30,default="",blank=True)
    val5name=models.CharField(max_length=30,default="",blank=True)
    val6name=models.CharField(max_length=30,default="",blank=True)
    val7name=models.CharField(max_length=30,default="",blank=True)
    val8name=models.CharField(max_length=30,default="",blank=True)
    val9name=models.CharField(max_length=30,default="",blank=True)
    val10name=models.CharField(max_length=30,default="",blank=True)
    val11name=models.CharField(max_length=30,default="",blank=True)
    val12name=models.CharField(max_length=30,default="",blank=True)
    val13name=models.CharField(max_length=30,default="",blank=True)
    val14name=models.CharField(max_length=30,default="",blank=True)
    val15name=models.CharField(max_length=30,default="",blank=True)
    val16name=models.CharField(max_length=30,default="",blank=True)
    val17name=models.CharField(max_length=30,default="",blank=True)
    val18name=models.CharField(max_length=30,default="",blank=True)
    val19name=models.CharField(max_length=30,default="",blank=True)
    val20name=models.CharField(max_length=30,default="",blank=True)

    val1type = models.IntegerField(default=-1)
    val2type = models.IntegerField(default=-1)
    val3type = models.IntegerField(default=-1)
    val4type = models.IntegerField(default=-1)
    val5type = models.IntegerField(default=-1)
    val6type = models.IntegerField(default=-1)
    val7type = models.IntegerField(default=-1)
    val8type = models.IntegerField(default=-1)
    val9type = models.IntegerField(default=-1)
    val10type = models.IntegerField(default=-1)
    val11type = models.IntegerField(default=-1)
    val12type = models.IntegerField(default=-1)
    val13type = models.IntegerField(default=-1)
    val14type = models.IntegerField(default=-1)
    val15type = models.IntegerField(default=-1)
    val16type = models.IntegerField(default=-1)
    val17type = models.IntegerField(default=-1)
    val18type = models.IntegerField(default=-1)
    val19type = models.IntegerField(default=-1)
    val20type = models.IntegerField(default=-1)

    val1keep = models.IntegerField(default=-1)
    val2keep = models.IntegerField(default=-1)
    val3keep = models.IntegerField(default=-1)
    val4keep = models.IntegerField(default=-1)
    val5keep = models.IntegerField(default=-1)
    val6keep = models.IntegerField(default=-1)
    val7keep = models.IntegerField(default=-1)
    val8keep = models.IntegerField(default=-1)
    val9keep = models.IntegerField(default=-1)
    val10keep = models.IntegerField(default=-1)
    val11keep = models.IntegerField(default=-1)
    val12keep = models.IntegerField(default=-1)
    val13keep = models.IntegerField(default=-1)
    val14keep = models.IntegerField(default=-1)
    val15keep = models.IntegerField(default=-1)
    val16keep = models.IntegerField(default=-1)
    val17keep = models.IntegerField(default=-1)
    val18keep = models.IntegerField(default=-1)
    val19keep = models.IntegerField(default=-1)
    val20keep = models.IntegerField(default=-1)

    val1default = models.IntegerField(default=-1)
    val2default = models.IntegerField(default=-1)
    val3default = models.IntegerField(default=-1)
    val4default = models.IntegerField(default=-1)
    val5default = models.IntegerField(default=-1)
    val6default = models.IntegerField(default=-1)
    val7default = models.IntegerField(default=-1)
    val8default = models.IntegerField(default=-1)
    val9default = models.IntegerField(default=-1)
    val10default = models.IntegerField(default=-1)
    val11default = models.IntegerField(default=-1)
    val12default = models.IntegerField(default=-1)
    val13default = models.IntegerField(default=-1)
    val14default = models.IntegerField(default=-1)
    val15default = models.IntegerField(default=-1)
    val16default = models.IntegerField(default=-1)
    val17default = models.IntegerField(default=-1)
    val18default = models.IntegerField(default=-1)
    val19default = models.IntegerField(default=-1)
    val20default = models.IntegerField(default=-1)
class Day(models.Model):
    descr = models.CharField(max_length=8,default="fixit")
    notes = models.CharField(max_length=30,default="",blank=True)
    int1 = models.DecimalField(default=-1,max_digits=5,decimal_places=2)
    int2 = models.DecimalField(default=-1,max_digits=5,decimal_places=2)
    int3 = models.DecimalField(default=-1,max_digits=5,decimal_places=2)
    int4 = models.DecimalField(default=-1,max_digits=5,decimal_places=2)
    int5 = models.DecimalField(default=-1,max_digits=5,decimal_places=2)
    int6 = models.DecimalField(default=-1,max_digits=5,decimal_places=2)
    int7 = models.DecimalField(default=-1,max_digits=5,decimal_places=2)
    int8 = models.DecimalField(default=-1,max_digits=5,decimal_places=2)
    int9 = models.DecimalField(default=-1,max_digits=5,decimal_places=2)
    int10 = models.DecimalField(default=-1,max_digits=5,decimal_places=2)
    int11 = models.DecimalField(default=-1,max_digits=5,decimal_places=2)
    int12 = models.DecimalField(default=-1,max_digits=5,decimal_places=2)
    int13 = models.DecimalField(default=-1,max_digits=5,decimal_places=2)
    int14 = models.DecimalField(default=-1,max_digits=5,decimal_places=2)
    int15 = models.DecimalField(default=-1,max_digits=5,decimal_places=2)
    int16 = models.DecimalField(default=-1,max_digits=5,decimal_places=2)
    int17 = models.DecimalField(default=-1,max_digits=5,decimal_places=2)
    int18 = models.DecimalField(default=-1,max_digits=5,decimal_places=2)
    int19 = models.DecimalField(default=-1,max_digits=5,decimal_places=2)
    int20 = models.DecimalField(default=-1,max_digits=5,decimal_places=2)